[project]
name = "conceptual-pathfinding-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.8.1",
    "openai-agents>=0.6.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
]
